blog/urls.py
from django.urls import path
from . import views
from .views import post_list_api,post_detail_api
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    #post views
    # path('', views.PostListView.as_view(), name='post_list'),
    path('', views.post_list, name='post_list'),
#     path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('tag/<str:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/',
         views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    path('blog/', post_list_api.as_view(), name='post_list_api'),
    path('blog/<int:pk>/', post_detail_api.as_view(), name='post_detail_api'),
    
]

mysite/urls.py
from django.contrib import admin
# from django.conf.urls import url
from django.urls import path, include
# from django.conf.urls import include
# from django.urls import re_path
# from django.urls.re_path import
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls
from rest_framework_swagger.views import get_swagger_view


DOCS_TITLE="Blog API"
DOCS_DESCRIPTION="SomeThings"

sitemaps = {
    'posts':PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap'),
    path('api/v1/',include('blog.urls')),
    path('api-auth/',include('rest_framework.urls')),
    # url(r'^api/v1/rest-auth/', include('rest_auth.urls')),
    path('api/v1/rest-auth/' , include('rest_auth.urls')),
    path('api/v1/rest-auth/registration/' , include('rest_auth.registration.urls')),
    path('schema/',get_schema_view(DOCS_TITLE,DOCS_DESCRIPTION)),
    path('docs/',include_docs_urls(DOCS_TITLE,DOCS_DESCRIPTION)),
    path('swagger-docs/',get_swagger_view(DOCS_TITLE)),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
from jalali_date import date2jalali, datetime2jalali


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'),)
    title = models.CharField(max_length=250)
    slug = models.CharField(max_length=250, unique_for_date='publish')
    body = models.TextField()
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    publish = models.DateTimeField(default=timezone.now)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager()

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day, self.slug])

    def get_created_jalali(self):
        return datetime2jalali(self.create)

    def get_update_jalali(self):
        return datetime2jalali(self.update)

    def get_publish_jalali(self):
        return datetime2jalali(self.publish)


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

    def get_created_jalali(self):
        return datetime2jalali(self.created)

    def get_update_jalali(self):
        return datetime2jalali(self.updated)

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
    query=forms.CharField()

blog/views.py
from re import search
from tkinter.messagebox import NO
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.db.models import Count
from taggit.models import Tag
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank

from .models import Post, Comment

from rest_framework import generics, permissions
from .permissions import IsAuthorOrReadOnly
from blog.serializers import PostSerializer


# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published', publish__year=year,
                             publish__month=month, publish__day=day)

    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':

        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return HttpResponseRedirect(request.path_info)
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    # print(post_tags_ids)
    similar_posts = Post.published\
        .filter(tags__in=post_tags_ids)\
        .distinct()\
        .exclude(id=post.id)

    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
        .order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'new_comment': new_comment,
                                                     'comment_form': comment_form,
                                                     'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data #To bind data to a form, pass the data as a dictionary as the first parameter to your Form class constructor
            # ... Send email
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'info@mySite.com',
                      [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # results=Post.published.annotate(
            #     search=SearchVector('title','body'),
            # ).filter(search=query)
        # step2
            # search_vector=SearchVector('title','body')
            # search_query=SearchQuery(query)
            # results=Post.published.annotate(
            #     search=search_vector,rank=SearchRank(search_vector,search_query)
            # ).filter(search=search_query).order_by('-rank')

            search_vector = SearchVector(
                'title', weight='A') + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                rank=SearchRank(search_vector, search_query)
            ).filter(rank__gte=0.3).order_by('-rank')

    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results
                   }
                  )

# CREATE API


class post_list_api(generics.ListCreateAPIView):
    # permission_classes=(permissions.AllowAny,)
    queryset = Post.objects.all()
    serializer_class = PostSerializer


class post_detail_api(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (IsAuthorOrReadOnly,)
    queryset = Post.objects.all()
    serializer_class = PostSerializer

blog/templates/blog/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html dir="rtl">

<head>
  <title>{% block title %}{% endblock %}</title>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css"
    integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">


  <link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.5.3/css/bootstrap.min.css"
    integrity="sha384-JvExCACAZcHNJEc7156QaHXTnQL3hQBixvj5RV5buE7vgnNEzzskDtx9NQ4p6BJe" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.rtlcss.com/bootstrap/v4.5.3/js/bootstrap.bundle.min.js"
    integrity="sha384-40ix5a3dj6/qaC7tfz0Yr+p9fqWLzzAXiwxVLt9dw7UjQzGYw6rWRhFAnRapuQyK"
    crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">


  <link type="text/css" href="{% static 'css/blog.css' %}" rel="stylesheet">

  <style>
    @font-face {
      font-family: 'IranSanse';
      src: local('IranSanse'),
      url('{% static "fonts/eot/IRANSansWeb.eot" %}') format('eot'),
      url('{% static "fonts/ttf/IRANSansWeb.ttf" %}') format('ttf'),
      url('{% static "fonts/woff/IRANSansWeb.woff" %}') format('woff'),
      url('{% static "fonts/woff2/IRANSansWeb.woff2" %}') format('woff2');
    }
  </style>
</head>



<body class="bg2">


   <nav id="navbar_top" class="navbar navbar-expand-lg navbar-light bg-light">
      <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand titr" href="{% url 'blog:post_list' %}">
          اقتصاد فردا
        </a>
      </nav>

    <ul class="navbar-nav mr-auto">
    </ul>
    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2 se-inp" type="search" placeholder="جستجو" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">جستجو</button>
    </form> -->
    <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'blog:post_search' %}">
      <input class="form-control mr-sm-2 se-inp" type="search" name="query" placeholder="جستجو" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">جستجو</button>
  </form>
   </nav>
 




  <!-- <div class="topnav">
  <div id="navbar">
    <nav class="navbar navbar-expand-lg navbar-light bg-light  ">
      <nav class="navbar navbar-light bg-light">
    <a class="navbar-brand titr" href="{% url 'blog:post_list' %}">
      اقتصاد فردا
    </a>
  </nav>
    <ul class="navbar-nav mr-auto">

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2 se-inp" type="search" placeholder="جستجو" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">جستجو</button>
    </form>
    </nav>
  </div>
  </div> -->
  

  <!-- <div class="topnav">
    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-fixed-top ">
      <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand titr" href="{% url 'blog:post_list' %}">
          <img src="" width="30" height="30" class="d-inline-block align-top" alt="">
          اقتصاد فردا
        </a>
      </nav>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2 se-inp" type="search" placeholder="جستجو" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">جستجو</button>
        </form>
      </div>
    </nav>
  </div> -->

  <div id="sidebar">

    <h3>آخرین اخبار</h3>
    {% show_latest_posts 3 %}
    <br>
    <h3>بیشترین نظرات</h3>
    {% get_most_commented_posts as most_commented_posts %}
    <ul>
      {% for post in most_commented_posts %}
      <li>
        <a  class="sidebar-a" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </li>
      {% endfor %}
    </ul>
    <div id="content">
      <p>
        <a  href="{% url 'blog:post_feed' %}" class="rss-btn"><i class="bi bi-rss"></i> RSS</a>
      </p>
    </div>
  </div>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
<!-- 
  <script>
    // When the user scrolls the page, execute myFunction
window.onscroll = function() {myFunction()};

// Get the navbar
var navbar = document.getElementById("navbar");

// Get the offset position of the navbar
var sticky = navbar.offsetTop;

// Add the sticky class to the navbar when you reach its scroll position. Remove "sticky" when you leave the scroll position
function myFunction() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky")
  } else {
    navbar.classList.remove("sticky");
  }
}
  </script> -->
  <script>
    document.addEventListener("DOMContentLoaded", function(){
  window.addEventListener('scroll', function() {
      if (window.scrollY > 90) {
        document.getElementById('navbar_top').classList.add('fixed-top');
        // add padding top to show content behind navbar
        navbar_height = document.querySelector('.navbar').offsetHeight;
        document.body.style.paddingTop = navbar_height + 'px';
      } else {
        document.getElementById('navbar_top').classList.remove('fixed-top');
         // remove padding top from body
        document.body.style.paddingTop = '0';
      } 
  });
}); 
  </script>
</body>

</html>