blog/urls.py
from django.urls import path
from . import views
from .views import post_list_api,post_detail_api
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    #post views
    # path('', views.PostListView.as_view(), name='post_list'),
    path('', views.post_list, name='post_list'),
#     path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('tag/<str:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/',
         views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    path('blog/', post_list_api.as_view(), name='post_list_api'),
    path('blog/<int:pk>/', post_detail_api.as_view(), name='post_detail_api'),
    
]

mysite/urls.py
from django.contrib import admin
# from django.conf.urls import url
from django.urls import path, include
# from django.conf.urls import include
# from django.urls import re_path
# from django.urls.re_path import
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls
from rest_framework_swagger.views import get_swagger_view


DOCS_TITLE="Blog API"
DOCS_DESCRIPTION="SomeThings"

sitemaps = {
    'posts':PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap'),
    path('api/v1/',include('blog.urls')),
    path('api-auth/',include('rest_framework.urls')),
    # url(r'^api/v1/rest-auth/', include('rest_auth.urls')),
    path('api/v1/rest-auth/' , include('rest_auth.urls')),
    path('api/v1/rest-auth/registration/' , include('rest_auth.registration.urls')),
    path('schema/',get_schema_view(DOCS_TITLE,DOCS_DESCRIPTION)),
    path('docs/',include_docs_urls(DOCS_TITLE,DOCS_DESCRIPTION)),
    path('swagger-docs/',get_swagger_view(DOCS_TITLE)),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
from jalali_date import date2jalali, datetime2jalali


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'),)
    title = models.CharField(max_length=250)
    slug = models.CharField(max_length=250, unique_for_date='publish')
    body = models.TextField()
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    publish = models.DateTimeField(default=timezone.now)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager()

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day, self.slug])

    def get_created_jalali(self):
        return datetime2jalali(self.create)

    def get_update_jalali(self):
        return datetime2jalali(self.update)

    def get_publish_jalali(self):
        return datetime2jalali(self.publish)


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

    def get_created_jalali(self):
        return datetime2jalali(self.created)

    def get_update_jalali(self):
        return datetime2jalali(self.updated)

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
    query=forms.CharField()

blog/views.py
from re import search
from tkinter.messagebox import NO
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.db.models import Count
from taggit.models import Tag
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank

from .models import Post, Comment

from rest_framework import generics, permissions
from .permissions import IsAuthorOrReadOnly
from blog.serializers import PostSerializer


# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published', publish__year=year,
                             publish__month=month, publish__day=day)

    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':

        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return HttpResponseRedirect(request.path_info)
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    # print(post_tags_ids)
    similar_posts = Post.published\
        .filter(tags__in=post_tags_ids)\
        .distinct()\
        .exclude(id=post.id)

    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
        .order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'new_comment': new_comment,
                                                     'comment_form': comment_form,
                                                     'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data #To bind data to a form, pass the data as a dictionary as the first parameter to your Form class constructor
            # ... Send email
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'info@mySite.com',
                      [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # results=Post.published.annotate(
            #     search=SearchVector('title','body'),
            # ).filter(search=query)
        # step2
            # search_vector=SearchVector('title','body')
            # search_query=SearchQuery(query)
            # results=Post.published.annotate(
            #     search=search_vector,rank=SearchRank(search_vector,search_query)
            # ).filter(search=search_query).order_by('-rank')

            search_vector = SearchVector(
                'title', weight='A') + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                rank=SearchRank(search_vector, search_query)
            ).filter(rank__gte=0.3).order_by('-rank')

    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results
                   }
                  )

# CREATE API


class post_list_api(generics.ListCreateAPIView):
    # permission_classes=(permissions.AllowAny,)
    queryset = Post.objects.all()
    serializer_class = PostSerializer


class post_detail_api(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (IsAuthorOrReadOnly,)
    queryset = Post.objects.all()
    serializer_class = PostSerializer

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<div class="detail-bar">
  <div class="item">
    <p class="post-title">{{ post.title }}</p>
  </div>
  <div>
    <p class="date de-date">
      {{ post.get_publish_jalali }}
    </p>
    <p>
      برچسب ها:
      {% for tag in post.tags.all %}
      <a class="tags " href="{% url 'blog:post_list_by_tag' tag.slug %}">
        {{ tag.name }}
      </a>
      {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
  </div>

</div>


<!-- <p class="date">
  Published {{ post.publish }} by {{ post.author }}
</p>
<p class="tags">
  Tags:
  {% for tag in post.tags.all %}
  <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
    {{ tag.name }}
  </a>
  {% if not forloop.last %}, {% endif %}
  {% endfor %}
</p> -->
<div class="post-bodyg post_de">
  {{ post.body|markdown }}
</div>

<p>
  <a class="sendtof" href="{% url 'blog:post_share' post.id %}">
    ارسال به یک دوست
  </a>
</p>


<h2>پیشنهاد برای شما</h2>
<br>
{% for post in similar_posts %}
<p>
  <a class="referpost" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>
{% empty %}
پیشنهادی برای شما وجود ندارد
<br>
{% endfor %}

{% with comments.count as total_comments %}
{% if total_comments %}
<h2>
  {{ total_comments }} نظر
</h2>
{%endif%}
{% endwith %}

{% for comment in comments %}
<div class="comment">
  <p class="date de-date info"> {{ comment.name }} &nbsp {{ comment.get_created_jalali | date:" Y/m/d h:m:s "}}</p>
  <div class="post-bodyg post_de">{{ comment.body }}</div>
</div>
{% empty %}
<p>نظری ثبت نشده است.</p>
{% endfor %}


{% if new_comment %}
<h2>نظر شما ارسال شد.</h2>
{% else %}
<h2>نظر خود را بنویسید.</h2>
<br>
<form method="post">
  <!-- {{ comment_form.as_p }} -->
  <div class="input-container">
    <label for="">نام</label>
    <input class="helper-text" required type="text" name="name" id="id_work">
  </div>
  <div class="input-container">
    <label for="">ایمیل</label>
    <input class="helper-text" required type="text" name="email" id="id_work">
  </div>
  <div class="input-container">
    <label for="">متن</label>
    <textarea class="helper-text " required type="text" name="body" id="txtArea" rows="10" cols="70"></textarea>
  </div>

  {% csrf_token %}
  <!-- <p><input type="submit" value="ارسال نظر"></p> -->
  <button class="btn btn-outline-success my-2 my-sm-0 " type="submit">ارسال نظر</button>
  <br>
</form>
<br><br>
{% endif %}



{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a class="sidebar-a " href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}
<!-- <h1>My Blog</h1> -->
{% if tag %}
<h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}

{% for post in posts %}
<a  class="post-title" style="display: block;" class="postq" href="{{ post.get_absolute_url }}">
  <div >
    <div>
      <p >
        {{ post.title }}
      </p>
    </div>
    <p class="tags">
      {% for tag in post.tags.all %}
        {{ tag.name }}
      {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>

    <div class="post-bodyg">
      {{ post.body |markdown|truncatewords:30 }}
    </div>
    <p class="date">
      {{ post.get_publish_jalali }}
      <!-- by {{ post.author }} -->
    </p>
  </div>
</a>
<!-- <hr style="width:100%", size="3", color=black>   -->
{% endfor %}
{% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}Search{% endblock %}
{% block content %}

    {% if query %}
        <!-- <h1>Posts containing "{{ query }}"</h1> -->
        <h3>
            {% with results.count as total_results %}
                 {{ total_results }} نتیجه  یافت شد.
                <!-- Found {{ total_results }} result {{ total_results|pluralize}} -->
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url}}">{{post.title}}</a></h4>
            {{ post.body | markdown|truncatewords_html:5}}
        {% empty %}
            <p> نتیجه‌ای یافت نشد! </p>
        {% endfor %}
        <p><a href="{% url 'blog:post_search' %}">جستجو</a></p>
    {% else %}
    <br><br>
        <!-- <h1> Search for posts</h1> -->
        <!-- <form method="get">
            {{ form.as_p}}
            <input type="submit" value="Search">
        </form> -->

        <form class="form-inline my-2 my-lg-0" method="get">
            <input class="form-control mr-sm-2 se-inp" type="search" name="query" placeholder="جستجو" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" value="Search" type="submit">جستجو</button>
        </form> 
    {% endif %}




{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}ارسال به یک دوست{% endblock %}

{% block content %}
  {% if sent %}
    <h1>ایمیل با موفقیت ارسال شد.</h1>
    <p>
      "{{ post.title }}" ارسال شد به {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <p class="post-title">اشتراک گذاری &nbsp "{{ post.title }}" &nbsp از طریق ایمیل</p>
    <form method="post">
      <!-- {{ form.as_p }} -->
      {% csrf_token %}
      <!-- <input type="submit" value="Send e-mail"> -->
      <div class="input-container">
        <label for="">نام</label>
        <input class="helper-text" required type="text" name="name" id="id_work">
    </div>
    <div class="input-container">
      <label for="">ایمیل</label>
      <input class="helper-text" required type="text" name="email" id="id_work">
    </div>
    <div class="input-container">
      <label for="">ارسال به </label>
      <input class="helper-text" required type="text" name="email" id="id_work">
    </div>
    <div class="input-container">
      <label for="">متن</label>
      <textarea class="helper-text " required type="text" name="body" id="txtArea" rows="10" cols="70"></textarea>
    </div>
    <button class="btn btn-outline-success my-2 my-sm-0 " type="submit" value="Send e-mail">ارسال پست</button>
    <br>

    </form>
  {% endif %}
{% endblock %}